carpetitas del front creadas
EcommerceProyect/KaroKids pull request #5
Opened 2023-12-11 21:45 UTC by MaximilianoDienes

2023-12-11 21:46 UTC, GenaroCura approved these changes

2023-12-11 21:46 UTC, nicolaselozano approved these changes
reseteo de css oh si

2023-12-11 21:52 UTC, 4zin approved these changes

2023-12-11 21:53 UTC, NPirizSmith approved these changes

2023-12-12 00:20 UTC, nicolaselozano requested changes
remplazen por < Login />, por children no reciben nada los componentes

2023-12-12 00:20 UTC, nicolaselozano commented on client/src/App.jsx
> +      <Login></Login>
remplazen por < Login />, por children no reciben nada los componentes

2023-12-12 00:39 UTC, LuisaBarrios05 approved these changes

2023-12-12 02:05 UTC, chrivel14 approved these changes

2023-12-12 03:35 UTC, MaximilianoDienes reviewed
cambiado el login

2023-12-12 16:07 UTC, nicolaselozano approved these changes

2023-12-12 19:15 UTC, merged